# Основы работы с QGIS и NextGIS

:::{.callout-note}
Здесь расширить, больше рассказать о QGIS, показать его удобство, подчеркнуть перспективы его применения.
:::

**QGIS** – это географическая информационная система с открытым исходным кодом. Проект зародился в мае 2002 года и был создан как проект на SourceForge в июне того же года. В настоящее время QGIS работает на большинстве платформ Unix, Windows и macOS. QGIS разработан с использованием инструментария Qt (https://www.qt.io) и C++. QGIS работает быстро и имеет приятный, простой в использовании графический интерфейс пользователя (GUI).

**NextGIS** — это набор программ для создания тематических геоинформационных систем и сервисов. 

Некоторые продукты платформы:

**NextGIS Web** - Серверное программное обеспечение для хранения, визуализации и управления геоданными, гибкой настройки доступа к данным для пользователей. 

**NextGIS QGIS** -  Настольная ГИС для создания и редактирования данных, производства карт и выполнения аналитических операций. 

**NextGIS Mobile** - Мобильная ГИС, позволяющая создавать, редактировать и выгружать геоданные онлайн и офлайн. 

**NextGIS Data** - Актуальные геоданные в разных форматах, удобная структура слоёв, настроенные стили и проекты для ГИС. 
