project:
  type: book
  preview:
    port: 7502

book:
  title: "ГИС для пожарных подразделений"
  author: "Шамсудинов Г.Ю., Морозов В.В., Малютин О.С."
  date: today
  chapters:
    # Предисловие
    - index.qmd
    # Введение
    - intro.qmd

    # ГИС в деятельности пожарной охраны (где и как применяются)
    - gis_in_fire_service.qmd

    # Раздел 1. Основные сведения о ГИС
    - part: Раздел 1. Основные сведения о ГИС
      chapters:
        ## Пространственные данные
        - gis/qis_data.qmd
        ## Системы координат в ГИС
        - gis/qis_sk.qmd
        ## Модели данных: растровая модель данных
        - gis/qis_rasters.qmd
        ## Модели данных: векторная модель данных
        - gis/qis_vectors.qmd
        ## Способы хранения пространственных данных (форматы файлов, базы данных, сторонние сервисы)
        
        ## Обзор программного обеспечения (ПО) ГИС
        - gis/qis_software.qmd

    # Раздел 2. Основные сведения о NextGIS
    - part: Раздел 2. Основные сведения о NextGIS
      chapters:
        ## Все о системе NextGIS
        - nextgis/about_nextgis.qmd
        ## О настольной версии NextGIS QGIS
        - nextgis/nextgis_info.qmd
        ## О веб - версии NextGIS QGIS
        - nextgis/about_webgis.qmd
        ## О прочих сервисах и службах NextGIS

        ## Установка QGIS и NextGIS
        - nextgis/qgis_install.qmd




    # Раздел 3. Работа с пространственными данными
    - part: Раздел 3. Работа с пространственными данными
      chapters:
        ## Создание первой карты
        - about_qgis/qgis_importexport.qmd
        ## Использование различных картографических подложек

        ## Создание и основы работы с векторными слоями

        ## Загрузка векторных слоев из OSM (здания, дороги, реки и т.д.)

        ## Получение готовых карт от NextGIS

        ## Импорт векторных данных из электронных таблиц

        ## Импорт векторных данных из прочих картографических форматов

        ## Настройка стилей векторных слоев (точки)

        ## Настройка стилей векторных слоев (линии)

        ## Настройка стилей векторных слоев (полигоны)

        ## Основы работы с растровыми слоями

        ## Настройка растровых слоев


    ## Раздел 4. Основы пространственного анализа


    ## Раздел 5. Применение в задачах пожарной охраны
    - part: Раздел 4. Применение в задачах пожарной охраны
      chapters:
        ## Создание карты района выезда
        - fire_main/fm_ride_maps.qmd

        ## Ведение базы данных объектов в районе выезда

        ## Создание планшета водоисточников

        ## Создание и ведение базы данных водоисточников

        ## Анализ маршрутов следования
        - fire_main/fm_routes.qmd

        ## Расчет границ районов выезда пожарных подразделений
        - fire_main/fm_bounds.qmd

        ## Анализ параметров прибытия пожарных подразделений
        - fire_main/fm_arrival_times.qmd


    # Заключение
    - summary.qmd

    # Список источников
    - references.qmd


format:
  html:
    theme: cosmo
  docx:
    fig-align: center
    lang: ru
    reference-doc: custom-reference-doc.docx
    toc: false


csl: gost-r-7-0-5-2008-numeric.csl

bibliography: my_references.bib

crossref:
  fig-prefix: рис.      # по умолчанию "Figure"
  tbl-prefix: табл.     # по умолчанию "Table"
  title-delim: " --"    # разделитель номера и названия рисунка