project:
  type: book

book:
  title: "QGIS для пожарных подразделений"
  author: "ФИО"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - gis_in_fire_service.qmd
    - part: about_qgis.qmd
      chapters: 
        - about_qgis/qgis_basics.qmd
        - about_qgis/qgis_install.qmd
        - about_qgis/qgis_layers.qmd
        - about_qgis/qgis_importexport.qmd
    - part: fire_main.qmd
      chapters: 
        - fire_main/fm_inppw.qmd
        - fire_main/fm_inppw_planshets.qmd
        - fire_main/fm_ride_maps.qmd
    - part: garrysons.qmd
      chapters: 
        - garrysons/garry_map.qmd
        - garrysons/garry_borders.qmd
        - garrysons/garry_analize.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

lang: ru

