# Введение {.unnumbered}

Это руководство написано для сотрудников пожарных подразделений с целью помочь им в работе с такой картографической информацией как сведения об источниках наружного противопожарного водоснабжения, составление карт районов выезда, а также работой с модулем "Генезис" в ГИС программах NextGIS и QGIS.

## Основные преимущества использования QGIS

**Открытый исходный код:** Благодаря открытому исходному коду, QGIS доступен для всех пользователей без необходимости приобретения дорогостоящих лицензий. Это особенно важно для государственных структур, таких как пожарная охрана, где бюджетные ограничения могут стать препятствием для внедрения новых технологий.

**Широкий функционал:** QGIS предлагает широкий спектр возможностей для работы с географической информацией. Пользователи могут создавать и редактировать векторные и растровые слои, выполнять пространственный анализ, создавать тематические карты и многое другое. Эти функции делают QGIS идеальным инструментом для создания и обновления справочников водоисточников и карт районов выезда.

**Поддержка различных форматов данных:** QGIS поддерживает большинство популярных форматов географических данных, включая Shapefile, GeoTIFF, KML/KMZ и другие. Это позволяет легко импортировать и экспортировать данные между различными системами и платформами, обеспечивая совместимость с другими программными продуктами (например: 2ГИС, Яндекс, Excel и др.).

**Плагиновая архитектура:** QGIS имеет множество плагинов для работы, благодаря которым пользователи могут расширять функциональность программы, добавляя дополнительные модули и инструменты, в Сибирской пожарно-спасательной Академии ГПС МЧС России создан плагин для проведения расчётов параметров реагирования пожарных подразделений, численности и оптимальных мест их размещения под названием **"Генезис"**.

Таким образом, переход на использование цифровых карт и автоматизированных систем управления является необходимым шагом для модернизации пожарных подразделений и обеспечения их соответствия вызовам современного мира.
