## Системы координат в ГИС
**Пространственные данные** - цифровые данные о пространственных объектах, включающие сведения об их местоположении и свойствах, пространственных и не пространственных атрибутах. Для того чтобы пространственные данные могли отображаться в едином пространстве, у них должна быть определена система координат, проекция и точка начала отсчета. 

**Координирование пространства** - один из ключевых феноменов географии, который прокладывает для неё путь в мир математики и науки вообще, а ГИС важный инструмент познания пространственных отношений.

Системы координат существуют:

**Локальные** - В локальных системах координат хорошо работать на малой территории, но каждый исследователь может работать в своей системе координат и они не могут передавать результаты своих изысканий друг другу.

**Глобальные** - В глобальных  координатных пространствах пользователь однозначно определяет свое местоположение в пространстве и может обогащать свой проект добавляет в него данные из открытых датасетов, также они позволяют использовать подложки для своих проектов.

***Географическая система координат*** - базовый и основной способ определения положения объектов на поверхности. На Земной сфере или эллипсоиде вращения любая точка поверхности определяется двумя двугранными углами.

Систем координат можно предложить бесконечно много, как отобразить данные из разных СК.

Среди всего их множества есть стандартные системы координат, которые используются чаще всего.

Для их описания и комплексного учёта ведётся база данных EPSG Geodetic Parameter Dataset. Каталог наиболее востребованных систем координат, каждой из них назначен свой уникальный код.

Например, **EPSG:3857** – система координат Pseudo Mercator, которая используется по умолчанию в множестве картографических веб-сервисов, таких как Google Maps, OpenStreetMap и др.
