## Обзор программного обеспечения (ПО) ГИС
Пространственные данные, или геопространственные данные, или географические данные, или геоданные — самый большой по объему вид, потому что практически всё, что окружает нас в реальном мире, может быть описано в терминах пространственных данных.

К пространственным данным относится геометрическая форма объекта, его местоположение в пространстве и его наименование. Для обработки таких объемов данных используются геоинформационные системы.

В ГОСТ Р 52438–2005 закреплено Понятие ГИС и звучит следующим образом: **геоинформационная система;** **ГИС:** Информационная система, оперирующая пространственными данными.

Т.е. ГИС обладает всеми свойствами информационной системы (ИС) с отличием только в данных.

Широко используется понятие, содержащее в своем определении характеристики ИС и звучит оно следующим образом.

**Геоинформационные системы или ГИС** — система сбора, хранения, анализа и графической визуализации пространственных (географических) данных и связанной с ними информации о необходимых объектах.

Например, понятие геоинформационной системы также используется как инструмент или приложение, позволяющее пользователям искать, анализировать и редактировать пространственную информацию о любом объекте или теме.

Например, есть ПО ГИС, хорошо решающее проблемы, возникающие при ведении городского хозяйства – учет и мониторинг состояния инженерных коммуникаций, транспортных сетей, управления территорией и информационной поддержки.