# Веб ГИС

**Веб ГИС** - это система, предназначенная для хранения пространственных данных и управления ими через веб-интерфейс или API.

*С помощью Веб ГИС вы сможете:*

1. Загружать и хранить растровые и векторные геоданные;

2. Подключать геоданные из внешних баз данных и геосервисов;

3. Отображать геоданные на веб-картах, а также публиковать их с помощью стандартных протоколов;

4. Гибко настраивать стили визуализации геоданных;

5. Редактировать атрибуты загруженных геоданных, добавлять их описания и фотографии;

6. Работать с геоданными через мобильное приложение NextGIS Mobile и настольное приложение NextGIS QGIS;

7. Создавать собственные клиентские приложения, используя NextGIS API

Веб ГИС позволяет загружать и хранить геоданные из локальных источников в следующих форматах:

**Растровые** - GeoTIFF (стандартный растровый стиль поддерживает RGB или RGBA, для остальных вариантов можно использовать стиль QGIS);

**Векторные** - ESRI Shapefile, GeoJSON, GeoPackage, GML, KML, CSV или XLSX. Для CSV и XLSX поддерживаются только точки, координаты должны быть в колонках lat и lon.

Если нужно загрузить данные в другом формате, вы можете использовать NextGIS Connect.

